"""add request occasion

Revision ID: 3134729c92c7
Revises: a185375abda1
Create Date: 2026-09-02 14:35:15.246278
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3134729c92c7'
down_revision: str | None = 'a185375abda1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('occasion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'occasion')
    # ### end Alembic commands ###
