"""add outfit render_url

Revision ID: 67742676dfdf
Revises: 5617aa8f195d
Create Date: 2026-09-01 18:45:08.047827
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '67742676dfdf'
down_revision: str | None = '5617aa8f195d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('render_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits', 'render_url')
    # ### end Alembic commands ###
