"""create garments table

Revision ID: 6e584b6353be
Revises: d5b4b720a699
Create Date: 2026-08-24 17:28:28.900819
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6e584b6353be'
down_revision: str | None = 'd5b4b720a699'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garments_status'), 'garments', ['status'], unique=False)
    op.create_index(op.f('ix_garments_user_id'), 'garments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garments_user_id'), table_name='garments')
    op.drop_index(op.f('ix_garments_status'), table_name='garments')
    op.drop_table('garments')
    # ### end Alembic commands ###
