"""avatar base image nullable for generated path

Revision ID: a185375abda1
Revises: 6457adf08226
Create Date: 2026-09-02 13:58:02.198919
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a185375abda1'
down_revision: str | None = '6457adf08226'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avatars', 'base_image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('avatars', 'base_image_public_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avatars', 'base_image_public_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('avatars', 'base_image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
